import type { User } from "./types";

export interface LocalUser extends User {
    password: string;
    description?: string;
}

export const LOCAL_USERS: LocalUser[] = [
    {
        userName: "State Administrator",
        loginUserName: "admin",
        userDesignation: "System Administrator",
        primaryRoleCode: "ADMIN",
        roleTitle: "System Admin",
        password: "123456",
        defaultPath: "/dashboard",
        department: "Women & Child Development Department",
        description: "Full administrative access across all modules",
    },
    {
        userName: "State Directorate Official",
        loginUserName: "state",
        userDesignation: "State Level Nodal Officer (W&CD)",
        primaryRoleCode: "STATE",
        roleTitle: "State Nodal Officer",
        password: "123456",
        defaultPath: "/dashboard",
        department: "Directorate of Women & Child Development, Odisha",
        description: "State-level monitoring, allocation sanctions and scheme oversight",
    },
    {
        userName: "Smt. Arundhati Ray",
        loginUserName: "dswo",
        userDesignation: "District Social Welfare Officer (DSWO)",
        primaryRoleCode: "DSWO",
        roleTitle: "DSWO Officer (L1)",
        password: "123456",
        defaultPath: "/dashboard",
        department: "District Social Welfare Office",
        district: "Khordha",
        description: "L1 Verification & Remarks on new SHG applications",
    },
    {
        userName: "Smt. Manorama Mishra",
        loginUserName: "cdpo",
        userDesignation: "Child Development Project Officer (CDPO)",
        primaryRoleCode: "CDPO",
        roleTitle: "CDPO Project Officer",
        password: "123456",
        defaultPath: "/dashboard",
        department: "ICDS Project Office",
        block: "Bhubaneswar Urban",
        district: "Khordha",
        description: "Project level supervision, indent verification and fund allocation",
    },
    {
        userName: "Sri Bikash Mohapatra",
        loginUserName: "blf",
        userDesignation: "Block Level Federation (BLF) Coordinator",
        primaryRoleCode: "BLF",
        roleTitle: "BLF Coordinator (L2)",
        password: "123456",
        defaultPath: "/dashboard",
        department: "Mission Shakti / BLF",
        block: "Bhubaneswar",
        district: "Khordha",
        description: "L2 Capacity Verification & Shortlisting",
    },
    {
        userName: "Block Selection Committee",
        loginUserName: "blc",
        userDesignation: "Block Level Committee Chair / BDO",
        primaryRoleCode: "BLC",
        roleTitle: "Block Level Committee (BLC)",
        password: "123456",
        defaultPath: "/dashboard",
        department: "Block Administration / BDO Office",
        block: "Bhubaneswar",
        district: "Khordha",
        description: "Final Empanelment Selection, Tagging & Credential Generation",
    },
    {
        userName: "Smt. Basanti Nayak",
        loginUserName: "aww",
        userDesignation: "Anganwadi Worker (AWW)",
        primaryRoleCode: "AWW",
        roleTitle: "Anganwadi Worker (AWW)",
        password: "123456",
        defaultPath: "/dashboard",
        department: "Anganwadi Centre - Unit 8",
        block: "Bhubaneswar",
        district: "Khordha",
        description: "Anganwadi centre uniform delivery receipt and beneficiary distribution",
    },
    {
        userName: "Maa Tarini Self Help Group",
        loginUserName: "shg",
        userDesignation: "SHG President / Secretary",
        primaryRoleCode: "SHG",
        roleTitle: "SHG Applicant",
        password: "123456",
        defaultPath: "/track-wshg",
        department: "SHG Member",
        block: "Bhubaneswar",
        district: "Khordha",
        description: "SHG Application Submission & Real-Time Tracking",
    },
];
